# Generated by Django 4.0.4 on 2022-05-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_lastdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=models.CharField(choices=[('Permanent', 'Fulltime'), ('Internship', 'Internship'), ('Freelancing', 'Freelancing')], default='Permanent', max_length=100),
        ),
    ]
